//Generated by MRKPortal Yggdrasil

import Foundation

final class ContactSceneRouter: GenericRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

    //MARK: - GenericRouterProtocol
    func pop() {
        coordinator.pop()
    }
}

