//Generated by MRKPortal Yggdrasil

import SwiftUI

final class ContactSceneFactory: Factory {
    private lazy var router = GenericRouter(injector: injector, coordinator: coordinator)
    private lazy var presenter = ContactScenePresenter(router)
    
    override func build() -> AnyView {
        AnyView(ContactSceneView(presenter))
    }
}
