//Generated by MRKTrace Yggdrasil

import Foundation

protocol ContactSceneRouterProtocol {

}

final class ContactSceneRouter: ContactSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

}

