//Generated by MRKPortal Yggdrasil

import Foundation
import UIKit

protocol ContactScenePresenterProtocol: GenericScenePresenterProtocol {
    var contacts: [ContactType] { get }
    func didTapContact(_ type: ContactType)
}

final class ContactScenePresenter: ContactScenePresenterProtocol {
    
    @Published var contacts: [ContactType] = ContactType.allCases
    
	private let router: GenericRouterProtocol

	init(_ router: GenericRouterProtocol) {
		self.router = router
	}

    //MARK: - ContactScenePresenterProtocol

    func didTapContact(_ type: ContactType) {
        let urlString = switch type {
        case .mail:
            C.Contact.contactMail
        case .git:
            C.Contact.gitHubURL
        case .linkedIn:
            C.Contact.linkedInURL
        case .social:
            C.Contact.socialURL
        }
        
        guard let url = URL(string: urlString) else {
            return
        }

        UIApplication.shared.open(url)
    }

    //MARK: - GenericScenePresenterProtocol
    
    func pop() {
        router.pop()
    }
}

