//Generated by MRKPortal Yggdrasil

import Foundation

protocol ContactSceneInteractorProtocol {

}

final class ContactSceneInteractor: ContactSceneInteractorProtocol {

	init(_ injector: ServicesInjectorProtocol) {

    }

}

