//Generated by MRKTrace Yggdrasil

import SwiftUI

struct ExperiencesSceneView<P: ExperiencesScenePresenterProtocol>: View {

    private let presenter: P

    init(_ presenter: P) {
        self.presenter = presenter
    }

    var body: some View {
        Color.clear
    }
}
