//Generated by MRKTrace Yggdrasil

import SwiftUI

final class ExperiencesSceneFactory: Factory {
    private lazy var router = ExperiencesSceneRouter(injector, coordinator: coordinator)
    private lazy var interactor = ExperiencesSceneInteractor(injector)
    private lazy var presenter = ExperiencesScenePresenter(interactor, router: router)
    
    override func build() -> AnyView {
        AnyView(ExperiencesSceneView(presenter))
    }
}
