//Generated by MRKTrace Yggdrasil

import Foundation

protocol ExperiencesSceneInteractorProtocol {

}

final class ExperiencesSceneInteractor: ExperiencesSceneInteractorProtocol {

	init(_ injector: ServicesInjectorProtocol) {

    }

}

