//Generated by MRKTrace Yggdrasil

import Foundation

protocol ExperiencesScenePresenterProtocol {
    var distributor: DistributorProtocol { get }

    func didTapBack()
}

final class ExperiencesScenePresenter: ExperiencesScenePresenterProtocol {

	private let interactor: ExperiencesSceneInteractorProtocol
	private let router: ExperiencesSceneRouterProtocol

    let distributor: DistributorProtocol
    
	init(_ interactor: ExperiencesSceneInteractorProtocol, router: ExperiencesSceneRouterProtocol) {
		self.interactor = interactor
		self.router = router
        self.distributor = HiveDistributor(5)
	}

    func didTapBack() {
        router.pop()
    }
}

