//Generated by MRKTrace Yggdrasil

import SwiftUI

struct ExperiencesSceneView<P: ExperiencesScenePresenterProtocol>: View {

    private let presenter: P

    @State var animate = false
    
    init(_ presenter: P) {
        self.presenter = presenter
    }
    
    var body: some View {
        GeometryReader { reader in
            ZStack {
                Color
                    .base2
                ForEach(Array(presenter.distributor.positionGroups.enumerated()), id: \.offset) { radius, group in
                    ForEach(Array(group.enumerated()), id: \.offset) { _, pos in
                        let side = reader.size.width / 3
                        let delay = CGFloat(radius) * 0.15
                        Color.red
                            .clipShape(NgonShape(points: 6))
                            .frame(size: .s(side))
                            .transformEffect(.t(pos.x * side, y: pos.y * side))
                            .scaleEffect(animate ? 1 : 0.5)
                            .opacity(animate ? 1 : 0)
                            .animation(.bouncy(duration: 1, extraBounce: 0.5).delay(delay), value: animate)
                    }
                }
            }
        }
        .parallax(x: 50, y: 50)
        .gestureRouter(directions: [.right]) { _ in
            presenter.didTapBack()
        }
        .onAppear {
            animate.toggle()
        }
    }
}
