//Generated by MRKPortal Yggdrasil

import SwiftUI

final class MainSceneFactory: Factory {
    private lazy var router = MainSceneRouter(injector, coordinator: coordinator)
    private lazy var presenter = MainScenePresenter(router)
    
    override func build() -> AnyView {
        AnyView(MainSceneView(presenter))
    }
}
