//Generated by MRKTrace Yggdrasil

import Foundation

protocol MainScenePresenterProtocol {
    func didTapNext()
    func didTapBack()
}

final class MainScenePresenter: MainScenePresenterProtocol {

	private let interactor: MainSceneInteractorProtocol
	private let router: MainSceneRouterProtocol

	init(_ interactor: MainSceneInteractorProtocol, router: MainSceneRouterProtocol) {
		self.interactor = interactor
		self.router = router
        print("initialization")
	}
    
    func didTapNext() {
        router.nextScene()
    }
    
    func didTapBack() {
        router.previousScene()
    }
    
    deinit {
        print("deinit")
    }
}

