//Generated by MRKTrace Yggdrasil

import Foundation

protocol MainSceneInteractorProtocol {

}

final class MainSceneInteractor: MainSceneInteractorProtocol {

	init(_ injector: ServicesInjectorProtocol) {

    }

}

