//Generated by MRKPortal Yggdrasil

import Foundation

protocol MainScenePresenterProtocol {
    func didSwipe()
}

final class MainScenePresenter: MainScenePresenterProtocol {

	private let router: MainSceneRouterProtocol

	init(_ router: MainSceneRouterProtocol) {
		self.router = router
	}
    
    func didSwipe() {
        router.nextScene()
    }
}

