//Generated by MRKTrace Yggdrasil

import Foundation

protocol MainScenePresenterProtocol {
    func didTapNext()
}

final class MainScenePresenter: MainScenePresenterProtocol {

	private let interactor: MainSceneInteractorProtocol
	private let router: MainSceneRouterProtocol

	init(_ interactor: MainSceneInteractorProtocol, router: MainSceneRouterProtocol) {
		self.interactor = interactor
		self.router = router
	}
    
    func didTapNext() {
        router.nextScene()
    }
}

