//Generated by MRKTrace Yggdrasil

import Foundation

protocol MainSceneRouterProtocol {
    func nextScene()
    func previousScene()
}

final class MainSceneRouter: MainSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

    func nextScene() {
        coordinator.pushView(
            MainSceneFactory(
                coordinator: coordinator, 
                injector: injector
            )
        )
    }
    
    func previousScene() {
        coordinator.pop()
    }
}

