//Generated by MRKTrace Yggdrasil

import SwiftUI

struct MainSceneView<P: MainScenePresenterProtocol>: View {

    private let presenter: P

    init(_ presenter: P) {
        self.presenter = presenter
    }

    var body: some View {
        Image
            .miscLogo
            .resizable()
            .scaledToFit()
            .padding(.horizontal, 32)
    }
}
