//Generated by MRKPortal Yggdrasil

import Foundation

final class SkillsSceneRouter: GenericRouter {
    override func nextFactory(injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) -> Factory {
        PrinciplesSceneFactory (
            coordinator: coordinator,
            injector: injector
        )
    }
}

