//Generated by MRKPortal Yggdrasil

import Foundation

protocol SkillsSceneRouterProtocol {
    func pop()
}

final class SkillsSceneRouter: SkillsSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

    func pop() {
        coordinator.pop()
    }
}

