//Generated by MRKPortal Yggdrasil

import SwiftUI

final class SkillsSceneFactory: Factory {
    private lazy var router = SkillsSceneRouter(injector: injector, coordinator: coordinator)
    private lazy var interactor = SkillsSceneInteractor(injector)
    private lazy var presenter = SkillsScenePresenter(interactor, router: router)
    
    override func build() -> AnyView {
        AnyView(SkillsSceneView(presenter))
    }
}
