//Generated by MRKPortal Yggdrasil

import Foundation

protocol SkillsSceneInteractorProtocol {
    func fetchSkills() async throws -> [SkillEntity]
}

final class SkillsSceneInteractor: SkillsSceneInteractorProtocol {
    
    private let api: APIServiceProtocol
    
    init(_ injector: ServicesInjectorProtocol) {
        self.api = injector.api
    }
    
    func fetchSkills() async throws -> [SkillEntity] {
        try await api.getSkills().results
    }
}

