//Generated by MRKTrace Yggdrasil

import SwiftUI

struct PrinciplesSceneView<P: PrinciplesScenePresenterProtocol>: View {

    private let presenter: P

    init(_ presenter: P) {
        self.presenter = presenter
    }

    var body: some View {
        Color.clear
    }
}
