//Generated by MRKPortal Yggdrasil

import Foundation

protocol PrinciplesSceneRouterProtocol {
    func previousScene()
}

final class PrinciplesSceneRouter: PrinciplesSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

    func previousScene() {
        coordinator.pop()
    }
}

