//Generated by MRKTrace Yggdrasil

import Foundation

protocol PrinciplesSceneInteractorProtocol {

}

final class PrinciplesSceneInteractor: PrinciplesSceneInteractorProtocol {

	init(_ injector: ServicesInjectorProtocol) {

    }
}

