//Generated by MRKTrace Yggdrasil

import SwiftUI

final class PrinciplesSceneFactory: Factory {
    private lazy var router = PrinciplesSceneRouter(injector, coordinator: coordinator)
    private lazy var interactor = PrinciplesSceneInteractor(injector)
    private lazy var presenter = PrinciplesScenePresenter(interactor, router: router)
    
    override func build() -> AnyView {
        AnyView(PrinciplesSceneView(presenter))
    }
}
