//Generated by MRKTrace Yggdrasil

import Foundation

protocol PrinciplesSceneRouterProtocol {

}

final class PrinciplesSceneRouter: PrinciplesSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

}

