//Generated by MRKTrace Yggdrasil

import Foundation

protocol AboutScenePresenterProtocol {
    func didTapBack()
    func didSwipeRight()
    func didSwipeLeft()
}

final class AboutScenePresenter: AboutScenePresenterProtocol {

	private let interactor: AboutSceneInteractorProtocol
	private let router: AboutSceneRouterProtocol

	init(_ interactor: AboutSceneInteractorProtocol, router: AboutSceneRouterProtocol) {
		self.interactor = interactor
		self.router = router
	}

    func didTapBack() {
        router.pop()
    }
    
    func didSwipeLeft() {
        router.leftScene()
    }
    
    func didSwipeRight() {
        router.rightScene()
    }
}

