//Generated by MRKPortal Yggdrasil

import Foundation

protocol AboutSceneInteractorProtocol {

}

final class AboutSceneInteractor: AboutSceneInteractorProtocol {

	init(_ injector: ServicesInjectorProtocol) {

    }

}

