//Generated by MRKPortal Yggdrasil

import SwiftUI

struct AboutSceneView<P: AboutScenePresenterProtocol>: View {

    private let presenter: P

    init(_ presenter: P) {
        self.presenter = presenter
    }

    var body: some View {
        ZStack {
            Color
                .base2
            Text("Rmember kids!\n Quality over quantity")
        }
        .gestureRouter(directions: [.left, .down]) { direction in
            switch direction {
            case .down:
                presenter.didTapBack()
            default:
                presenter.didSwipeLeft()
            }
        }
    }
}
