//Generated by MRKPortal Yggdrasil

import Foundation

protocol AboutSceneRouterProtocol {
    func pop()
    func leftScene()
}

final class AboutSceneRouter: AboutSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }
    
    func pop() {
        coordinator.pop()
    }

    
    func leftScene() {
        coordinator.pushView(
            factory: SkillsSceneFactory(coordinator: coordinator, injector: injector),
            direction: .left
        )
    }
}

