//Generated by MRKTrace Yggdrasil

import Foundation

protocol AboutSceneRouterProtocol {

}

final class AboutSceneRouter: AboutSceneRouterProtocol {

    private let injector: ServicesInjectorProtocol
    private let coordinator: NavigationCoordinator

    init(_ injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) {
        self.injector = injector
        self.coordinator = coordinator
    }

}

