//Generated by MRKPortal Yggdrasil

import SwiftUI

final class AboutSceneFactory: Factory {
    private lazy var router = AboutSceneRouter(injector, coordinator: coordinator)
    private lazy var presenter = GenericScenePresenter(router)
    
    override func build() -> AnyView {
        AnyView(AboutSceneView(presenter))
    }
}
