//Generated by MRKTrace Yggdrasil

import Foundation

protocol AboutScenePresenterProtocol {

}

final class AboutScenePresenter: AboutScenePresenterProtocol {

	private let interactor: AboutSceneInteractorProtocol
	private let router: AboutSceneRouterProtocol

	init(_ interactor: AboutSceneInteractorProtocol, router: AboutSceneRouterProtocol) {
		self.interactor = interactor
		self.router = router
	}

}

