//Generated by MRKPortal Yggdrasil

import Foundation

protocol ClientsSceneInteractorProtocol {

}

final class ClientsSceneInteractor: ClientsSceneInteractorProtocol {

	init(_ injector: ServicesInjectorProtocol) {

    }

}

