//Generated by MRKPortal Yggdrasil

import Foundation

final class ClientsSceneRouter: GenericRouter {
    override func nextFactory(injector: ServicesInjectorProtocol, coordinator: NavigationCoordinator) -> Factory {
        SummarySceneFactory (
            coordinator: coordinator,
            injector: injector
        )
    }
}
