//Generated by MRKPortal Yggdrasil

import SwiftUI

final class ClientsSceneFactory: Factory {
    private lazy var router = ClientsSceneRouter(injector, coordinator: coordinator)
    private lazy var interactor = ClientsSceneInteractor(injector)
    private lazy var presenter = ClientsScenePresenter(interactor, router: router)
    
    override func build() -> AnyView {
        AnyView(ClientsSceneView(presenter))
    }
}
